---
abstract: 'a generic client for talking to restful web services'
author:
  - 'Mark Jason Dominus (陶敏修) <mjd@plover.com>'
build_requires:
  Data::Dumper: 0
  HTTP::Response: 0
  Test::More: 0
  perl: 5.006
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: REST-Consumer
requires:
  Carp: 0
  File::Path: 0
  HTTP::Headers: 0
  HTTP::Request: 0
  JSON::XS: 0
  LWP::UserAgent: 0
  URI: 0
  overload: 0
  strict: 0
  warnings: 0
version: 0.08
