---
abstract: 'General client for interacting with json data in HTTP Restful services'
author:
  - 'Chris Becker <cbecker@shutterstock.com>, Travis Beck <travis@shutterstock.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.76, CPAN::Meta::Converter version 2.132620'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: REST-Consumer
no_index:
  directory:
    - t
    - inc
requires:
  File::Path: 1.08
  HTTP::Request: 0
  JSON::XS: 0
  LWP: 0
  LWP::UserAgent::Paranoid: 0.94
  Test::CheckManifest: 0.9
  Test::More: 0
  Test::Resub: 2.01
  Time::HiRes: 0
  URI: 0
version: 1.00
